package:
    name: sf_dia
    version: 1.0.0

source:
    path: ..

build:
    number: 0

requirements:
    build:
        - python

    run:
        - python
        - detector_integration_api >=1.0.2

build:
  entry_points:
    - dia_sf = sf_dia.start_server:main

about:
    home: https://github.com/paulscherrerinstitute/sf_dia
